language: php

cache:
    directories:
        - $HOME/.composer/cache/files

branches:
  only:
    - master

php:
    - '7.1'
    - '7.2'
    - nightly

matrix:
    fast_finish: true
    include:
        - php: '7.1'
          env:
              - COMPOSER_FLAGS='--prefer-lowest'
              - SYMFONY_VERSION='~4.3.0'
        - php: '7.2'
          env: SYMFONY_VERSION='~4.3.0'
    allow_failures:
        - php: nightly

before_install:
    - set -eo pipefail
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
    - phpenv config-rm xdebug.ini || true
    - |
      if [ -n "$SYMFONY_VERSION" ]; then
          composer require --dev --no-update symfony/symfony "symfony/symfony:${SYMFONY_VERSION}"
      fi
    - composer update --prefer-dist $COMPOSER_FLAGS

script:
    - bin/phpunit
    - php bin/console psysh -V

notifications:
    email: false
